/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/traffic/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total road traffic per country */
        get: operations["TrafficController_getCountryTraffic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traffic/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Traffic distribution by vehicle type */
        get: operations["TrafficController_getVehicleTraffic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traffic/observations/{countryCode}/{vehicleCode}/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or replace a single observation */
        put: operations["TrafficController_updateObservation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CountryTrafficResponse: {
            data: {
                countryCode: string;
                countryName: string;
                value: number;
            }[];
            meta: {
                year: number;
                unitCode: string;
                unitLabel: string;
            };
        };
        VehicleTrafficResponse: {
            data: {
                vehicleCode: string;
                vehicleName: string;
                value: number;
            }[];
            meta: {
                year: number;
                unitCode: string;
                unitLabel: string;
            };
        };
        Observation: {
            countryCode: string;
            vehicleCode: string;
            year: number;
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TrafficController_getCountryTraffic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Total traffic distance per country */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryTrafficResponse"];
                };
            };
        };
    };
    TrafficController_getVehicleTraffic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Traffic distance per vehicle type, summed across countries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleTrafficResponse"];
                };
            };
        };
    };
    TrafficController_updateObservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                vehicleCode: "TOTAL" | "LOR_RTRN" | "MOTO_MOP" | "CAR" | "BUS_MCO_TRO";
                countryCode: "EE" | "ES" | "HU" | "RO" | "SE" | "CH";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: number;
                };
            };
        };
        responses: {
            /** @description The stored observation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"];
                };
            };
        };
    };
}
